import os
import re
import json

def generate_progress_bar(completed, total):
    if total == 0:
        return "░░░░░░░░░░ 0/0"
    percentage = int((completed / total) * 10)
    bar = "█" * percentage + "░" * (10 - percentage)
    return f"{bar} {completed}/{total}"

def update_readme():
    # Load the data generated by the GH API step in your workflow
    with open('project_data.json', 'r') as f:
        data = json.load(f)

    items = data['data']['user']['projectV2']['items']['nodes']
    
    # Process project items to count sub-tasks
    # Note: This logic assumes you are using the 'Status' field and Sub-issues
    phases = {
        "Phase 1": {"done": 0, "total": 0},
        "Phase 2": {"done": 0, "total": 0},
        "Phase 3": {"done": 0, "total": 0},
        "Phase 4": {"done": 0, "total": 0},
        "Phase 5": {"done": 0, "total": 0},
        "Phase 6": {"done": 0, "total": 0},
        "Phase 7": {"done": 0, "total": 0},
        "Phase 8": {"done": 0, "total": 0},
        "Phase 9": {"done": 0, "total": 0},
    }

    for item in items:
        title = item['content'].get('title', '')
        summary = item['content'].get('subIssuesSummary', {'total': 0, 'completed': 0})
        
        for phase in phases:
            if phase in title:
                phases[phase]['total'] += summary['total']
                phases[phase]['done'] += summary['completed']

    # Read README
    with open('README.md', 'r') as f:
        content = f.read()

    # Update the table rows using Regex
    for phase, counts in phases.items():
        new_bar = generate_progress_bar(counts['done'], counts['total'])
        # Matches the phase row and replaces the progress bar column
        pattern = rf"(\| {phase}:.*? \| .*? \| )(.*?)( \|)"
        content = re.sub(pattern, rf"\1{new_bar}\3", content)

    # Write back to README
    with open('README.md', 'w') as f:
        f.write(content)

if __name__ == "__main__":
    update_readme()
